### ISSUE TITLE
Command line parameters should resemble git diff

### ISSUE THREAD

**Issue by marcus-downing** [tommarshall/git-diff-ansible-vault#14]
The command line parameters for git diff between two branches look like:
```sh
git diff branchname..HEAD -- path/to/file
```
The parameters for this command are:
```sh
git diff-ansible-vault -r branchname -p path/to/file
```
It would be nicer if the parameters for this command were in line with the standard git form of parameters.
```sh
git diff-ansible-vault branchname..HEAD -- path/to/file
```
Other parameters such as `-v`, `--no-color` etc can remain unaltered, provided - as with other git commands - they happen before the `--` divider.

**Comment by tommarshall** [comment]
This appears to be a duplicate of https://github.com/tommarshall/git-diff-ansible-vault/issues/4

**Comment by marcus-downing** [comment]
True. The title of that issue didn't register as similar, but in effect it is.
